namespace DependencyModules.Conventions;

/// <summary>
/// The types a module implements to declare conventions, emitted into the consumer's compilation
/// through <c>RegisterPostInitializationOutput</c>.
/// </summary>
/// <remarks>
/// Shipped as source rather than in a runtime package for two reasons. They carry no behaviour —
/// nothing ever implements <see cref="ConventionDefinitions"/>, because the generator reads the
/// declarations out of the method body at compile time and the body never runs — so a runtime
/// assembly would contain nothing but empty contracts. And emitting them <c>internal</c> keeps
/// them off the consumer's public surface, so declaring conventions adds nothing to their API.
///
/// This is a fixed contract rather than something built from a model, so it is a literal rather
/// than CSharpAuthor output. Every other writer in this codebase generates from a model and uses
/// CSharpAuthor; this one has no model.
/// </remarks>
public static class ConventionContractSource {

    /// <summary>
    /// The hint name the contract is added under.
    /// </summary>
    public const string HintName = "DependencyModules.Conventions.Contracts.g.cs";

    /// <summary>
    /// The namespace the emitted types live in, and the metadata prefix the generator matches
    /// declarations against.
    /// </summary>
    public const string Namespace = "DependencyModules.Conventions";

    /// <summary>
    /// The interface a module implements to opt into convention registration.
    /// </summary>
    public const string ConventionModule = "IConventionModule";

    /// <summary>
    /// The method the generator reads. Implemented explicitly, so the name is fixed.
    /// </summary>
    public const string ConventionMethod = "Conventions";

    public const string Source =
        """
        // <auto-generated/>
        #nullable enable

        namespace DependencyModules.Conventions {

            /// <summary>
            /// Implement this on a [DependencyModule] class to register services by convention
            /// instead of attributing each one.
            /// </summary>
            /// <remarks>
            /// <para>
            /// <b>The body of <c>Conventions</c> is never executed.</b> It is read by the
            /// DependencyModules.Conventions source generator at compile time, which resolves the
            /// matching types and emits ordinary registrations. Nothing implements
            /// <see cref="IConventionDefinitions"/> at run time and the method is never called.
            /// </para>
            /// <para>
            /// Because it is configuration rather than code, only a chain of the calls declared on
            /// <see cref="IConventionDefinitions"/> and <see cref="IConventionRegistration"/> can
            /// appear in it. Loops, conditionals, locals and calls to your own helpers cannot be
            /// evaluated at compile time and are reported as DM0009 rather than ignored.
            /// </para>
            /// <para>
            /// Implement it explicitly. An ordinary public implementation does not compile, because
            /// the parameter type is internal (CS0051).
            /// </para>
            /// <example>
            /// <code>
            /// [DependencyModule]
            /// public partial class DataModule : IConventionModule {
            ///     void IConventionModule.Conventions(IConventionDefinitions conventions) {
            ///         conventions.RegisterAll&lt;IRepository&gt;().AsScoped();
            ///         conventions.RegisterAll(typeof(IRequestHandler&lt;,&gt;)).AsTransient();
            ///     }
            /// }
            /// </code>
            /// </example>
            /// </remarks>
            [global::System.CodeDom.Compiler.GeneratedCode("DependencyModules.Conventions", "1.0.0")]
            internal interface IConventionModule {

                /// <summary>
                /// Declares this module's conventions. Read at compile time; never invoked.
                /// </summary>
                /// <param name="conventions">Receives the declarations.</param>
                void Conventions(IConventionDefinitions conventions);
            }

            /// <summary>
            /// Declares which types a module registers by convention.
            /// </summary>
            /// <remarks>
            /// Nothing implements this. The calls made on it are read from source at compile time.
            /// </remarks>
            [global::System.CodeDom.Compiler.GeneratedCode("DependencyModules.Conventions", "1.0.0")]
            internal interface IConventionDefinitions {

                /// <summary>
                /// Registers every type in this compilation that implements
                /// <typeparamref name="TService"/>, as <typeparamref name="TService"/>.
                /// </summary>
                /// <remarks>
                /// Matches a type that declares <typeparamref name="TService"/> directly, and one
                /// that declares an interface extending it — an interface saying it extends another
                /// is a deliberate statement that it is substitutable for it. Reaching a service
                /// type through a <i>base class</i> is not matched unless
                /// <see cref="IConventionRegistration.IncludeBaseClasses"/> is called, because
                /// extending a class is a statement about implementation reuse rather than about
                /// the contract, and every subclass added later would silently join the convention.
                ///
                /// A type carrying an explicit service attribute is never a convention candidate;
                /// the attribute always wins.
                /// </remarks>
                /// <typeparam name="TService">The service type to scan for and register as.</typeparam>
                IConventionRegistration RegisterAll<TService>();

                /// <summary>
                /// The <see cref="RegisterAll{TService}"/> overload for open generics, which cannot
                /// be written as a type argument: <c>RegisterAll(typeof(IHandler&lt;,&gt;))</c>.
                /// </summary>
                /// <remarks>
                /// Each match is registered against the <i>closed</i> interface it implements, so
                /// <c>CreateOrderHandler : IHandler&lt;CreateOrder, OrderId&gt;</c> registers
                /// <c>IHandler&lt;CreateOrder, OrderId&gt;</c>. A generic implementation that closes
                /// nothing registers as the open generic.
                /// </remarks>
                /// <param name="serviceType">The service type to scan for, open or closed.</param>
                IConventionRegistration RegisterAll(global::System.Type serviceType);
            }

            /// <summary>
            /// Configures what a <c>RegisterAll</c> declaration produces.
            /// </summary>
            /// <remarks>
            /// A lifetime is required. There is no default, because a lifetime nobody wrote down is
            /// the most expensive thing for a registration to get wrong; omitting one is DM0009.
            /// </remarks>
            [global::System.CodeDom.Compiler.GeneratedCode("DependencyModules.Conventions", "1.0.0")]
            internal interface IConventionRegistration {

                /// <summary>Registers the matches as singletons.</summary>
                IConventionRegistration AsSingleton();

                /// <summary>Registers the matches as scoped.</summary>
                IConventionRegistration AsScoped();

                /// <summary>Registers the matches as transient.</summary>
                IConventionRegistration AsTransient();

                /// <summary>
                /// Also matches types that reach the service type only through a base class.
                /// </summary>
                /// <remarks>
                /// Off by default. Turning it on picks up the common
                /// <c>CreateOrderValidator : AbstractValidator&lt;CreateOrder&gt;</c> shape, where
                /// the interface is declared on a base class, at the cost of every future subclass
                /// of that base joining the convention without anyone revisiting it.
                /// </remarks>
                IConventionRegistration IncludeBaseClasses();
            }
        }
        """;
}
