using System.Collections.Immutable;
using DependencyModules.SourceGenerator.Impl;
using DependencyModules.SourceGenerator.Impl.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DependencyModules.SourceGenerator;

/// <summary>
/// Reports <see cref="DependencyModuleDiagnostics.ModuleAttributeNamespaceNotImported"/> — DM0016.
/// </summary>
/// <remarks>
/// <para>
/// Read from syntax rather than from the semantic model, which is not optional here: the attribute
/// this checks for is generated by the very generator that is running, so it does not exist in the
/// compilation being examined and nothing about it can be resolved. Every assembly-level module
/// attribute looks unresolved from here, which is why the check is "is there a module by that name,
/// and could this file see it" rather than "did it bind".
/// </para>
/// <para>
/// It stays quiet unless it can name the fix. An attribute that matches no module in this
/// compilation is somebody else's; a module in the global namespace needs no import; a qualified
/// usage already says where to look.
/// </para>
/// </remarks>
internal static class AssemblyModuleAttributeDiagnostics {

    /// <summary>
    /// One compilation unit's assembly attributes and the namespaces in scope for them.
    /// </summary>
    internal sealed class UnitModel : IEquatable<UnitModel> {

        public UnitModel(
            string filePath,
            ImmutableArray<Usage> usages,
            ImmutableArray<string> fileUsings,
            ImmutableArray<string> globalUsings) {
            FilePath = filePath;
            Usages = usages;
            FileUsings = fileUsings;
            GlobalUsings = globalUsings;
        }

        /// <summary>The file these attributes were written in.</summary>
        public string FilePath { get; }

        public ImmutableArray<Usage> Usages { get; }

        /// <summary>Namespaces this file imports, which apply only to this file.</summary>
        public ImmutableArray<string> FileUsings { get; }

        /// <summary>Namespaces this file imports for the whole compilation.</summary>
        public ImmutableArray<string> GlobalUsings { get; }

        public bool Equals(UnitModel? other) =>
            other != null &&
            FilePath == other.FilePath &&
            Usages.SequenceEqual(other.Usages) &&
            FileUsings.SequenceEqual(other.FileUsings) &&
            GlobalUsings.SequenceEqual(other.GlobalUsings);

        public override bool Equals(object? obj) => Equals(obj as UnitModel);

        public override int GetHashCode() => Usages.Length * 397 ^ FileUsings.Length;
    }

    internal sealed class Usage : IEquatable<Usage> {

        public Usage(string name, Location location) {
            Name = name;
            Location = location;
        }

        /// <summary>The attribute name exactly as written, without any qualification.</summary>
        public string Name { get; }

        public Location Location { get; }

        public bool Equals(Usage? other) =>
            other != null && Name == other.Name && Location.Equals(other.Location);

        public override bool Equals(object? obj) => Equals(obj as Usage);

        public override int GetHashCode() => Name.GetHashCode();
    }

    internal static IncrementalValueProvider<ImmutableArray<UnitModel>> Collect(
        IncrementalGeneratorInitializationContext context) =>
        context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is CompilationUnitSyntax,
                static (syntaxContext, cancellation) => Read(syntaxContext, cancellation))
            .Where(static model => !model.Usages.IsEmpty || !model.GlobalUsings.IsEmpty)
            .Collect();

    private static UnitModel Read(GeneratorSyntaxContext context, CancellationToken cancellation) {
        cancellation.ThrowIfCancellationRequested();

        var unit = (CompilationUnitSyntax)context.Node;

        var usages = ImmutableArray.CreateBuilder<Usage>();
        var fileUsings = ImmutableArray.CreateBuilder<string>();
        var globalUsings = ImmutableArray.CreateBuilder<string>();

        foreach (var usingDirective in unit.Usings) {
            // An alias imports one name rather than a namespace, so it cannot bring a module
            // attribute into scope under the name this checks for.
            if (usingDirective.Alias != null || usingDirective.Name == null) {
                continue;
            }

            var target = usingDirective.GlobalKeyword.IsKind(SyntaxKind.GlobalKeyword)
                ? globalUsings
                : fileUsings;

            target.Add(usingDirective.Name.ToString());
        }

        foreach (var attributeList in unit.AttributeLists) {
            if (!attributeList.Target?.Identifier.IsKind(SyntaxKind.AssemblyKeyword) ?? true) {
                continue;
            }

            foreach (var attribute in attributeList.Attributes) {
                // A qualified usage already names where the attribute lives.
                if (attribute.Name is not SimpleNameSyntax simpleName) {
                    continue;
                }

                usages.Add(new Usage(simpleName.Identifier.Text, attribute.GetLocation()));
            }
        }

        return new UnitModel(
            unit.SyntaxTree.FilePath,
            usages.ToImmutable(),
            fileUsings.ToImmutable(),
            globalUsings.ToImmutable());
    }

    internal static void Report(
        SourceProductionContext context,
        ((ImmutableArray<(ModuleEntryPointModel Left, DependencyModuleConfigurationModel Right)> Modules,
            ImmutableArray<UnitModel> Units) Left, Compilation Right) data) {

        var input = data.Left;

        if (input.Units.IsDefaultOrEmpty || input.Modules.IsDefaultOrEmpty) {
            return;
        }

        // Modules from referenced assemblies are the case both these codes exist for, and neither
        // could see them: everything below was built from the modules declared here.
        var referenced = new ReferencedModuleLookup(data.Right);

        // A module in the global namespace needs no import, and an auto-generated ApplicationModule
        // is never written by hand at the assembly level, so neither can produce this mistake.
        var modulesByName = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var (module, _) in input.Modules) {
            var moduleNamespace = module.EntryPointType.Namespace;

            if (string.IsNullOrEmpty(moduleNamespace) ||
                module.ModuleFeatures.HasFlag(ModuleEntryPointFeatures.AutoGenerateModule)) {
                continue;
            }

            modulesByName[module.EntryPointType.Name] = moduleNamespace;
        }

        // The file the generated ApplicationModule was built from, which is the only file whose
        // assembly-level module attributes are composed into anything. Null when nothing generated
        // one — a class library, or a test project, where assembly attributes are read at run time
        // by the test integration instead and are perfectly at home in any file.
        string? entryPointFile = null;

        foreach (var (module, _) in input.Modules) {
            if (module.ModuleFeatures.HasFlag(ModuleEntryPointFeatures.AutoGenerateModule)) {
                entryPointFile = module.FileLocation;
                break;
            }
        }

        var globalUsings = new HashSet<string>(StringComparer.Ordinal);

        foreach (var unit in input.Units) {
            foreach (var globalUsing in unit.GlobalUsings) {
                globalUsings.Add(globalUsing);
            }
        }

        foreach (var unit in input.Units) {
            foreach (var usage in unit.Usages) {
                context.CancellationToken.ThrowIfCancellationRequested();

                // Written as [assembly: Foo] or [assembly: FooAttribute]; both name module Foo.
                var moduleNamespace = LocalModuleNamespace(modulesByName, usage.Name);

                // Declared here, or shipped by something this project references. The imported
                // lookup comes first because it is the cheap one and the one a building project
                // takes; the exhaustive walk is only worth doing for a name that resolved to
                // nothing, which is a build that is already red.
                moduleNamespace ??= referenced.FindImported(
                    usage.Name, unit.FileUsings.Concat(globalUsings));

                moduleNamespace ??= referenced.FindAnywhere(usage.Name);

                if (moduleNamespace == null) {
                    continue;
                }

                if (!unit.FileUsings.Contains(moduleNamespace) && !globalUsings.Contains(moduleNamespace)) {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DependencyModuleDiagnostics.ModuleAttributeNamespaceNotImported,
                            usage.Location,
                            usage.Name,
                            moduleNamespace));

                    // It does not compile yet, so which file it belongs in is a later question.
                    continue;
                }

                if (entryPointFile != null &&
                    !string.IsNullOrEmpty(unit.FilePath) &&
                    !string.Equals(unit.FilePath, entryPointFile, StringComparison.Ordinal)) {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DependencyModuleDiagnostics.AssemblyModuleAttributeNotComposed,
                            usage.Location,
                            usage.Name,
                            System.IO.Path.GetFileName(entryPointFile)));
                }
            }
        }
    }

    /// <summary>The namespace of a module declared in this compilation, or null.</summary>
    private static string? LocalModuleNamespace(Dictionary<string, string> modulesByName, string name) {
        if (modulesByName.TryGetValue(name, out var found)) {
            return found;
        }

        return name.EndsWith("Attribute", StringComparison.Ordinal) &&
               modulesByName.TryGetValue(
                   name.Substring(0, name.Length - "Attribute".Length), out found)
            ? found
            : null;
    }
}
