using DependencyModules.SourceGenerator.Impl;
using DependencyModules.SourceGenerator.Impl.Models;
using DependencyModules.Tests.Infrastructure;
using Microsoft.CodeAnalysis;
using Xunit;

namespace DependencyModules.Tests.GeneratorTests;

/// <summary>
/// The generator is configured through MSBuild properties surfaced as CompilerVisibleProperty in
/// the packaged build/*.targets. These tests pin the mapping from property value to generated code.
/// </summary>
public class ConfigurationTests {

    [Fact]
    public void ExcludeGeneratedCodeFromCoverage_DefaultsToOn() {
        var result = GeneratorTestHarness.Run(ModuleWithService);

        result.AssertNoErrors();
        Assert.Contains("ExcludeFromCodeCoverage", result.SourceContaining("Dependencies"));
    }

    [Fact]
    public void ExcludeGeneratedCodeFromCoverage_False_OmitsTheAttribute() {
        var result = GeneratorTestHarness.Run(
            ModuleWithService,
            new Dictionary<string, string> { ["ExcludeGeneratedCodeFromCoverage"] = "false" });

        result.AssertNoErrors();
        Assert.DoesNotContain("ExcludeFromCodeCoverage", result.SourceContaining("Dependencies"));
    }

    [Fact]
    public void ExcludeGeneratedCodeFromCoverage_IsCaseInsensitive() {
        var result = GeneratorTestHarness.Run(
            ModuleWithService,
            new Dictionary<string, string> { ["ExcludeGeneratedCodeFromCoverage"] = "FALSE" });

        result.AssertNoErrors();
        Assert.DoesNotContain("ExcludeFromCodeCoverage", result.SourceContaining("Dependencies"));
    }

    /// <summary>
    /// RootNamespace is applied to the ApplicationModule that gets generated for a top-level
    /// statement Program.cs; explicitly declared modules keep whatever namespace they are written in.
    /// </summary>
    [Fact]
    public void RootNamespace_NamesTheAutoGeneratedApplicationModule() {
        var result = GeneratorTestHarness.Run(
            new Dictionary<string, string> {
                ["Program.cs"] =
                    """
                    using DependencyModules.Runtime.Attributes;

                    System.Console.WriteLine("hello");
                    """,
                ["Services.cs"] =
                    """
                    namespace TestNamespace;

                    public interface IThing;

                    [DependencyModules.Runtime.Attributes.SingletonService]
                    public class Thing : IThing;
                    """
            },
            new Dictionary<string, string> { ["RootNamespace"] = "ConfiguredRoot" },
            OutputKind.ConsoleApplication);

        result.AssertNoErrors();
        Assert.Contains("namespace ConfiguredRoot", result.SourceContaining("ApplicationModule"));
    }

    [Fact]
    public void AutoGenerateModule_False_SuppressesTheApplicationModule() {
        var result = GeneratorTestHarness.Run(
            new Dictionary<string, string> {
                ["Program.cs"] =
                    """
                    System.Console.WriteLine("hello");
                    """,
                ["Services.cs"] =
                    """
                    using DependencyModules.Runtime.Attributes;

                    namespace TestNamespace;

                    public interface IThing;

                    [SingletonService]
                    public class Thing : IThing;

                    [DependencyModule]
                    public partial class TestModule;
                    """
            },
            new Dictionary<string, string> { ["DependencyModules_AutoGenerateModule"] = "false" },
            OutputKind.ConsoleApplication);

        result.AssertNoErrors();
        Assert.DoesNotContain(result.GeneratedSources.Keys, key => key.Contains("ApplicationModule"));
    }

    [Theory]
    [InlineData("Try", RegistrationType.Try)]
    [InlineData("Add", RegistrationType.Add)]
    [InlineData("Replace", RegistrationType.Replace)]
    [InlineData("TryEnumerable", RegistrationType.TryEnumerable)]
    [InlineData("RegistrationType.Try", RegistrationType.Try)]
    [InlineData("", RegistrationType.Add)]
    [InlineData("nonsense", RegistrationType.Add)]
    public void GetRegistrationType_ParsesKnownValuesAndFallsBackToAdd(string input, RegistrationType expected) {
        Assert.Equal(expected, BaseSourceGenerator.GetRegistrationType(input));
    }

    [Fact]
    public void DependencyModulesRegistrationType_ChangesTheDefaultRegistrationMethod() {
        var result = GeneratorTestHarness.Run(
            ModuleWithService,
            new Dictionary<string, string> { ["DependencyModules_RegistrationType"] = "Try" });

        result.AssertNoErrors();
        Assert.Contains("TryAdd", result.SourceContaining("Dependencies"));
    }

    private const string ModuleWithService =
        """
        using DependencyModules.Runtime.Attributes;

        namespace TestNamespace;

        public interface IThing;

        [SingletonService]
        public class Thing : IThing;

        [DependencyModule]
        public partial class TestModule;
        """;
}
