using System.Collections.Immutable;
using CSharpAuthor;
using DependencyModules.SourceGenerator.Impl.Models;
using DependencyModules.SourceGenerator.Impl.Utilities;
using DependencyModules.Tests.Infrastructure;
using Xunit;

namespace DependencyModules.Tests.GeneratorTests;

/// <summary>
/// EntryModelUtil decides the generated file names and which entry points survive consolidation.
/// Getting consolidation wrong either drops a module's registrations or emits duplicate files.
/// </summary>
public class EntryModelUtilTests {

    [Fact]
    public void GenerateFileName_CombinesNamespaceTypeAndSuffix() {
        var model = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("My.Namespace", "MyModule"));

        Assert.Equal("My.Namespace.MyModule.Dependencies.g.cs", EntryModelUtil.GenerateFileName(model, "Dependencies"));
    }

    [Fact]
    public void GenerateFileName_ForTheGlobalNamespace_UsesAPlaceholder() {
        var model = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("", "MyModule"));

        Assert.Equal("blank-namespace.MyModule.Module.g.cs", EntryModelUtil.GenerateFileName(model, "Module"));
    }

    [Fact]
    public void EnsureNamespace_GivesAutoGeneratedModulesTheRootNamespace() {
        var model = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            entryPointType: TypeDefinition.Get("", "ApplicationModule"));

        var result = EntryModelUtil.EnsureNamespace(model, ModelFactory.Configuration(rootNamespace: "ConfiguredRoot"));

        Assert.Equal("ConfiguredRoot", result.EntryPointType.Namespace);
    }

    [Fact]
    public void EnsureNamespace_LeavesAutoGeneratedModulesThatAlreadyHaveANamespace() {
        var model = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            entryPointType: TypeDefinition.Get("Existing", "ApplicationModule"));

        var result = EntryModelUtil.EnsureNamespace(model, ModelFactory.Configuration(rootNamespace: "ConfiguredRoot"));

        Assert.Equal("Existing", result.EntryPointType.Namespace);
    }

    [Fact]
    public void EnsureNamespace_LeavesExplicitlyDeclaredModulesAlone() {
        var model = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("", "DeclaredModule"));

        var result = EntryModelUtil.EnsureNamespace(model, ModelFactory.Configuration(rootNamespace: "ConfiguredRoot"));

        Assert.Equal("", result.EntryPointType.Namespace);
    }

    [Fact]
    public void Consolidate_KeepsADeclaredModule() {
        var model = ModelFactory.EntryPoint();

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(model));

        Assert.Same(model, Assert.Single(entryPoints));
    }

    [Fact]
    public void Consolidate_KeepsAnAutoGeneratedModuleDeclaredInTheProjectsProgramFile() {
        var model = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            fileLocation: Path.Combine("/project/", "Program.cs"));

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(model));

        Assert.Single(entryPoints);
    }

    /// <summary>
    /// A Program.cs belonging to a referenced project must not generate an ApplicationModule here.
    /// </summary>
    [Fact]
    public void Consolidate_DropsAnAutoGeneratedModuleFromAnotherProject() {
        var model = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            fileLocation: "/somewhere-else/Program.cs");

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(model));

        Assert.Empty(entryPoints);
    }

    [Fact]
    public void Consolidate_WithAutoGenerateDisabled_DropsAutoGeneratedModules() {
        var model = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            fileLocation: Path.Combine("/project/", "Program.cs"));

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(
            Input(model, ModelFactory.Configuration(autoGenerateEntry: false)));

        Assert.Empty(entryPoints);
    }

    [Fact]
    public void Consolidate_WithAutoGenerateDisabled_KeepsDeclaredModules() {
        var model = ModelFactory.EntryPoint();

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(
            Input(model, ModelFactory.Configuration(autoGenerateEntry: false)));

        Assert.Single(entryPoints);
    }

    [Fact]
    public void Consolidate_GroupsModelsSharingANamespaceAndName() {
        var first = ModelFactory.EntryPoint(fileLocation: "/project/A.cs");
        var second = ModelFactory.EntryPoint(fileLocation: "/project/B.cs");

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(first, second));

        Assert.Single(entryPoints);
    }

    /// <summary>
    /// A partial module declared alongside an auto-generated one wins: the developer's declaration
    /// carries the configuration.
    /// </summary>
    [Fact]
    public void Consolidate_PrefersTheDeclaredModuleOverTheAutoGeneratedOne() {
        var auto = ModelFactory.EntryPoint(
            features: ModuleEntryPointFeatures.AutoGenerateModule,
            entryPointType: TypeDefinition.Get("TestNamespace", "SharedName"));
        var declared = ModelFactory.EntryPoint(
            entryPointType: TypeDefinition.Get("TestNamespace", "SharedName"),
            useMethod: "UseIt");

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(auto, declared));

        Assert.Same(declared, Assert.Single(entryPoints));
    }

    [Fact]
    public void Consolidate_KeepsDistinctModulesSeparate() {
        var first = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("TestNamespace", "First"));
        var second = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("TestNamespace", "Second"));

        var (entryPoints, _) = EntryModelUtil.ConsolidateEntryPointModels(Input(first, second));

        Assert.Equal(2, entryPoints.Count);
    }

    [Fact]
    public void Consolidate_ReturnsTheConfigurationItWasGiven() {
        var configuration = ModelFactory.Configuration(rootNamespace: "SomeRoot");

        var (_, returned) = EntryModelUtil.ConsolidateEntryPointModels(
            Input(ModelFactory.EntryPoint(), configuration));

        Assert.Same(configuration, returned);
    }

    [Fact]
    public void UniqueId_IsStableForTheSameType() {
        var first = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("A.B", "Module"));
        var second = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("A.B", "Module"));

        Assert.Equal(first.UniqueId(), second.UniqueId());
    }

    [Fact]
    public void UniqueId_DiffersBetweenTypes() {
        var first = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("A.B", "ModuleOne"));
        var second = ModelFactory.EntryPoint(entryPointType: TypeDefinition.Get("A.B", "ModuleTwo"));

        Assert.NotEqual(first.UniqueId(), second.UniqueId());
    }

    private static ImmutableArray<(ModuleEntryPointModel, DependencyModuleConfigurationModel)> Input(
        params ModuleEntryPointModel[] models) =>
        Input(ModelFactory.Configuration(), models);

    private static ImmutableArray<(ModuleEntryPointModel, DependencyModuleConfigurationModel)> Input(
        ModuleEntryPointModel model, DependencyModuleConfigurationModel configuration) =>
        Input(configuration, model);

    private static ImmutableArray<(ModuleEntryPointModel, DependencyModuleConfigurationModel)> Input(
        DependencyModuleConfigurationModel configuration, params ModuleEntryPointModel[] models) =>
        models.Select(model => (model, configuration)).ToImmutableArray();
}
