using System.Text;
using DependencyModules.SourceGenerator.Impl.Models;

namespace DependencyModules.SourceGenerator.Impl;

/// <summary>
/// Registers each generated wrapper as a decorator of the service it intercepts, and registers the
/// interceptors themselves so the wrapper can be constructed.
/// </summary>
public class InterceptorRegistrationWriter {

    public string Write(
        ModuleEntryPointModel entryPointModel,
        DependencyModuleConfigurationModel configurationModel,
        IReadOnlyList<InterceptorModel> models) {

        var builder = new StringBuilder();
        var moduleType = $"global::{Qualify(entryPointModel.EntryPointType.Namespace, entryPointModel.EntryPointType.Name)}";

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var indent = "";
        var namespaceName = entryPointModel.EntryPointType.Namespace;

        if (!string.IsNullOrEmpty(namespaceName)) {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            indent = "    ";
        }

        builder.AppendLine($"{indent}public partial class {entryPointModel.EntryPointType.Name}");
        builder.AppendLine($"{indent}{{");

        for (var i = 0; i < models.Count; i++) {
            var model = models[i];
            var methodName = $"ApplyInterceptor{i}";

            builder.AppendLine(
                $"{indent}    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(nameof({methodName}))]");
            builder.AppendLine(
                $"{indent}    private static int interceptorField{i} = " +
                $"global::DependencyModules.Runtime.Helpers.DependencyRegistry<{moduleType}>.AddDecorator(" +
                $"{methodName}, {model.Order});");
            builder.AppendLine();

            if (configurationModel.ExcludeGeneratedCodeFromCoverage) {
                builder.AppendLine($"{indent}    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            }

            builder.AppendLine(
                $"{indent}    private static void {methodName}(" +
                "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            builder.AppendLine($"{indent}    {{");

            // The interceptors have to be resolvable before the wrapper can be built. TryAdd keeps a
            // registration the developer made themselves, so lifetime and configuration stay theirs.
            foreach (var interceptor in model.Interceptors) {
                var interceptorType = $"global::{Qualify(interceptor.Namespace, interceptor.Name)}";

                builder.AppendLine(
                    $"{indent}        global::Microsoft.Extensions.DependencyInjection.Extensions" +
                    ".ServiceCollectionDescriptorExtensions.TryAddEnumerable(");
                builder.AppendLine(
                    $"{indent}            services,");
                builder.AppendLine(
                    $"{indent}            global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton(");
                builder.AppendLine(
                    $"{indent}                typeof(global::DependencyModules.Runtime.Interception.IInterceptor),");
                builder.AppendLine(
                    $"{indent}                typeof({interceptorType})));");
            }

            var serviceType = $"global::{Qualify(model.ServiceType.Namespace, model.ServiceType.Name)}";
            var wrapperName = $"{model.ImplementationType.Name.Replace(".", "_")}_Intercepted";
            var wrapperType = $"global::{Qualify(model.ImplementationType.Namespace, wrapperName)}";

            builder.AppendLine();
            builder.AppendLine($"{indent}        global::DependencyModules.Runtime.Helpers.DecoratorHelper.Decorate(");
            builder.AppendLine($"{indent}            services,");
            builder.AppendLine($"{indent}            typeof({serviceType}),");
            builder.AppendLine($"{indent}            typeof({wrapperType}));");
            builder.AppendLine($"{indent}    }}");

            if (i < models.Count - 1) {
                builder.AppendLine();
            }
        }

        builder.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(namespaceName)) {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static string Qualify(string namespaceName, string name) =>
        string.IsNullOrEmpty(namespaceName) ? name : $"{namespaceName}.{name}";
}
