using System.Text;
using DependencyModules.SourceGenerator.Impl.Models;

namespace DependencyModules.SourceGenerator.Impl;

/// <summary>
/// Writes the wrapper type that routes each call to an intercepted service through its interceptors.
/// </summary>
/// <remarks>
/// Written as text rather than through CSharpAuthor. The bodies need try/catch/finally, await, and
/// exact signature reproduction from Roslyn's own renderer; expressing that through a code-model API
/// would obscure the one thing that has to be read carefully, which is where the hooks sit relative
/// to the await.
/// </remarks>
public class InterceptorFileWriter {

    public string Write(InterceptorModel model, string wrapperName, string namespaceName) {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var indent = "";

        if (!string.IsNullOrEmpty(namespaceName)) {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            indent = "    ";
        }

        var serviceType = Global(model.ServiceType.Namespace, model.ServiceType.Name);

        builder.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        builder.AppendLine($"{indent}internal sealed class {wrapperName} : {serviceType}");
        builder.AppendLine($"{indent}{{");
        builder.AppendLine($"{indent}    private readonly {serviceType} _inner;");
        builder.AppendLine(
            $"{indent}    private readonly global::System.Collections.Generic.IReadOnlyList" +
            "<global::DependencyModules.Runtime.Interception.IInterceptor> _interceptors;");
        builder.AppendLine();
        builder.AppendLine(
            $"{indent}    public {wrapperName}({serviceType} inner, " +
            "global::System.Collections.Generic.IEnumerable" +
            "<global::DependencyModules.Runtime.Interception.IInterceptor> interceptors)");
        builder.AppendLine($"{indent}    {{");
        builder.AppendLine($"{indent}        _inner = inner;");
        builder.AppendLine(
            $"{indent}        _interceptors = global::System.Linq.Enumerable.ToArray(interceptors);");
        builder.AppendLine($"{indent}    }}");

        foreach (var member in model.Members) {
            builder.AppendLine();
            WriteMember(builder, indent + "    ", serviceType, member);
        }

        builder.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(namespaceName)) {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void WriteMember(StringBuilder builder, string indent, string serviceType, InterceptedMemberModel member) {
        // A member returning a task is awaited inside the wrapper so completion is reported when the
        // work finishes rather than when the task is handed back. Reporting on return is the classic
        // interception bug: every duration reads as near zero and every fault goes unseen.
        var isAsync = member.ReturnShape is ReturnShape.Task or ReturnShape.TaskOfValue
            or ReturnShape.ValueTask or ReturnShape.ValueTaskOfValue;

        var asyncModifier = isAsync ? "async " : "";
        var await = isAsync ? "await " : "";

        builder.AppendLine($"{indent}public {asyncModifier}{member.Declaration}");
        builder.AppendLine($"{indent}{{");
        builder.AppendLine(
            $"{indent}    var context = new global::DependencyModules.Runtime.Interception.InvocationContext(" +
            $"typeof({serviceType}), \"{member.Name}\");");
        builder.AppendLine();
        builder.AppendLine($"{indent}    for (var i = 0; i < _interceptors.Count; i++)");
        builder.AppendLine($"{indent}    {{");
        builder.AppendLine($"{indent}        _interceptors[i].OnEnter(in context);");
        builder.AppendLine($"{indent}    }}");
        builder.AppendLine();
        builder.AppendLine($"{indent}    try");
        builder.AppendLine($"{indent}    {{");

        var call = $"{await}_inner.{member.Name}({member.ArgumentList})";

        switch (member.ReturnShape) {
            case ReturnShape.Void:
            case ReturnShape.Task:
            case ReturnShape.ValueTask:
                builder.AppendLine($"{indent}        {call};");
                builder.AppendLine();
                WriteExitLoop(builder, indent + "        ");
                break;

            default:
                builder.AppendLine($"{indent}        var result = {call};");
                builder.AppendLine();
                WriteExitLoop(builder, indent + "        ");
                builder.AppendLine();
                builder.AppendLine($"{indent}        return result;");
                break;
        }

        builder.AppendLine($"{indent}    }}");
        builder.AppendLine($"{indent}    catch (global::System.Exception exception)");
        builder.AppendLine($"{indent}    {{");
        builder.AppendLine($"{indent}        for (var i = _interceptors.Count - 1; i >= 0; i--)");
        builder.AppendLine($"{indent}        {{");
        builder.AppendLine($"{indent}            _interceptors[i].OnError(in context, exception);");
        builder.AppendLine($"{indent}        }}");
        builder.AppendLine();
        builder.AppendLine($"{indent}        throw;");
        builder.AppendLine($"{indent}    }}");
        builder.AppendLine($"{indent}}}");
    }

    /// <summary>
    /// Exit runs in reverse, so interceptors unwind in the order they wrapped.
    /// </summary>
    private static void WriteExitLoop(StringBuilder builder, string indent) {
        builder.AppendLine($"{indent}for (var i = _interceptors.Count - 1; i >= 0; i--)");
        builder.AppendLine($"{indent}{{");
        builder.AppendLine($"{indent}    _interceptors[i].OnExit(in context);");
        builder.AppendLine($"{indent}}}");
    }

    private static string Global(string namespaceName, string name) =>
        string.IsNullOrEmpty(namespaceName) ? $"global::{name}" : $"global::{namespaceName}.{name}";
}
